services:
  app:
    build:
      context: './app'
      dockerfile: Dockerfile
    image: "app-golang:1.0.1"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s