services:
  mongodb-example:
    container_name: mongodb-example
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME= admin
      - MONGO_INITDB_ROOT_PASSWORD= password
      - MONGO_INITDB_DATABASE= admin
    ports:
      - "27017:27017"
    networks:
      - network_example
  mongo-express-example:
    container_name: mongo-express-example
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb-example
    networks:
      - network_example
    depends_on:
      - mongodb-example

networks:
  network-example:
    name: network-example
    driver: bridge