services:
  nginx-port1:
    container_name: nginx-port1
    image: nginx:latest
    ports:
      - protocol: TCP
        target: 80
        published: 8080
  nginx-port2:
    container_name: nginx-port2
    image: nginx:latest
    ports:
      - "8081:80"