services:
  nginx-example:
    container_name: nginx-example
    image: nginx:latest
    ports:
      - protocol: TCP
        target: 80
        published: 8080
    networks:
      - network_example

networks:
  network_example:
    name: network_example
    driver: bridge